# Generated by Django 3.2.5 on 2021-08-09 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadcomment',
            options={'ordering': ('-comment_time',), 'verbose_name': '帖子评论', 'verbose_name_plural': '帖子评论'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_focus',
            field=models.ManyToManyField(related_name='topic_focus_set', to='users.UserInfo', verbose_name='关注用户'),
        ),
        migrations.AlterField(
            model_name='userchatroomstatus',
            name='last_enter_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 11, 40, 12, 593578), verbose_name='上次浏览时间'),
        ),
    ]
