# Generated by Django 3.0.4 on 2024-03-27 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240316_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatroomstatus',
            name='last_enter_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 22, 29, 17, 290012), verbose_name='上次浏览时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='school_zone',
            field=models.IntegerField(choices=[(1, '主校区'), (2, '同济校区'), (3, '网安校区'), (4, '军山校区'), (5, '青山湖校区'), (6, '鄱阳湖校区'), (7, '抚州校区')], default=1, verbose_name='校区'),
        ),
    ]
